const productData = [
  {
    id: 1,
    code: '235896',
    name: 'Dragon Toy',
    image: './src/Images/dragon.jpeg',
    productType: "3DModel",
    price: 169,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nullam ac tortor vitae purus faucibus. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Porttitor rhoncus dolor purus non enim praesent. Convallis aenean et tortor at. Commodo elit at imperdiet dui accumsan sit. At erat pellentesque adipiscing commodo elit. Tellus in hac habitasse platea dictumst vestibulum rhoncus est. Aliquet nec ullamcorper sit amet risus. Non tellus orci ac auctor augue mauris.",
    dimensions: "20cm X 15cm",
    weight: "5",
  },
  {
    id: 2,
    code: '231696',
    name: 'Oni Mask',
    image: './src/Images/Oni.jpeg',
    productType: "3DModel",
    price: 159,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nullam ac tortor vitae purus faucibus. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Porttitor rhoncus dolor purus non enim praesent. Convallis aenean et tortor at. Commodo elit at imperdiet dui accumsan sit. At erat pellentesque adipiscing commodo elit. Tellus in hac habitasse platea dictumst vestibulum rhoncus est. Aliquet nec ullamcorper sit amet risus. Non tellus orci ac auctor augue mauris.",
    dimensions: "20cm X 15cm",
    weight: "5",
  },{
    id: 3,
    code: '239096',
    name: 'Dragon Toy',
    image: './src/Images/dragon.jpeg',
    productType: "3DModel",
    price: 169,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nullam ac tortor vitae purus faucibus. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Porttitor rhoncus dolor purus non enim praesent. Convallis aenean et tortor at. Commodo elit at imperdiet dui accumsan sit. At erat pellentesque adipiscing commodo elit. Tellus in hac habitasse platea dictumst vestibulum rhoncus est. Aliquet nec ullamcorper sit amet risus. Non tellus orci ac auctor augue mauris.",
    dimensions: "20cm X 15cm",
    weight: "5",
  },
  {
    id: 4,
    code: '233796',
    name: 'Oni Mask',
    image: './src/Images/Oni.jpeg',
    productType: "3DModel",
    price: 159,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nullam ac tortor vitae purus faucibus. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Porttitor rhoncus dolor purus non enim praesent. Convallis aenean et tortor at. Commodo elit at imperdiet dui accumsan sit. At erat pellentesque adipiscing commodo elit. Tellus in hac habitasse platea dictumst vestibulum rhoncus est. Aliquet nec ullamcorper sit amet risus. Non tellus orci ac auctor augue mauris.",
    dimensions: "20cm X 15cm",
    weight: "5",
  },{
    id: 5,
    code: '235486',
    name: 'Dragon Toy',
    image: './src/Images/dragon.jpeg',
    productType: "3DModel",
    price: 169,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nullam ac tortor vitae purus faucibus. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Porttitor rhoncus dolor purus non enim praesent. Convallis aenean et tortor at. Commodo elit at imperdiet dui accumsan sit. At erat pellentesque adipiscing commodo elit. Tellus in hac habitasse platea dictumst vestibulum rhoncus est. Aliquet nec ullamcorper sit amet risus. Non tellus orci ac auctor augue mauris.",
    dimensions: "20cm X 15cm",
    weight: "5",
  },
  {
    id: 6,
    code: '235815',
    name: 'Oni Mask',
    image: './src/Images/Oni.jpeg',
    productType: "3DModel",
    price: 159,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nullam ac tortor vitae purus faucibus. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Porttitor rhoncus dolor purus non enim praesent. Convallis aenean et tortor at. Commodo elit at imperdiet dui accumsan sit. At erat pellentesque adipiscing commodo elit. Tellus in hac habitasse platea dictumst vestibulum rhoncus est. Aliquet nec ullamcorper sit amet risus. Non tellus orci ac auctor augue mauris.",
    dimensions: "20cm X 15cm",
    weight: "5",
  }
];

export default productData;
